config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'login', to: 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  resources :users
  resources :user_sessions

  resources :books
  resources :posts
  resources :coordinators

  resources :buildings
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
  has_many :coordinator_workers
  # has_many :workers, through: :coordinator_workers

  # first direction
  has_many :subordinates, through: :coordinator_workers, class_name: "Worker"
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  before_action :set_coordinator, only: [:show, :edit, :update, :destroy]

  # GET /coordinators
  # GET /coordinators.json
  def index
    @coordinators = Coordinator.all
    @workers = Worker.all.sample(20).sort
  end

  # GET /coordinators/1
  # GET /coordinators/1.json
  def show
  end

  # GET /coordinators/new
  def new
    @coordinator = Coordinator.new
    @coordinator.subordinates.build
    # @workers = Worker.all.sample(20).sort
    @subordinates = Worker.all.sample(20).sort
  end

  # GET /coordinators/1/edit
  def edit
  end

  # POST /coordinators
  # POST /coordinators.json
  def create
    @coordinator = Coordinator.new(coordinator_params)

    respond_to do |format|
      if @coordinator.save
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully created.' }
        format.json { render :show, status: :created, location: @coordinator }
      else
        format.html { render :new }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinators/1
  # PATCH/PUT /coordinators/1.json
  def update
    respond_to do |format|
      if @coordinator.update(coordinator_params)
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        format.html { render :edit }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinators/1
  # DELETE /coordinators/1.json
  def destroy
    @coordinator.destroy
    respond_to do |format|
      format.html { redirect_to coordinators_url, notice: 'Coordinator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator
      @coordinator = Coordinator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coordinator_params
      # params.require(:coordinator).permit(:name, :coordinator_worker_ids)
      params.require(:coordinator).permit!
      # params.require(:post).permit(:title, comments_attributes: [:body])
      # params.require(:coordinator).permit(:name, workers_attributes: [:name])
    end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/views/coordinators/_form.html.erb
<%#= form_with(model: coordinator, local: true) do |form| %>
<%= simple_form_for @coordinator do |form| %>
  <% if @coordinator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coordinator.errors.count, "error") %> prohibited this coordinator from being saved:</h2>

      <ul>
      <% @coordinator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.association :subordinates, collection: @subordinates, as: :check_boxes %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coordinators/edit.html.erb
<h1>Editing Coordinator</h1>

<%= render 'form', coordinator: @coordinator %>

<%= link_to 'Show', @coordinator %> |
<%= link_to 'Back', coordinators_path %>

app/views/coordinators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coordinators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordinators.each do |coordinator| %>
      <tr>
        <td><%= coordinator.name %></td>
        <td><%= link_to 'Show', coordinator %></td>
        <td><%= link_to 'Edit', edit_coordinator_path(coordinator) %></td>
        <td><%= link_to 'Destroy', coordinator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coordinator', new_coordinator_path %>

app/views/coordinators/new.html.erb
<h1>New Coordinator</h1>

<%= render 'form', coordinator: @coordinator %>

<%= link_to 'Back', coordinators_path %>

app/views/coordinators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coordinator.name %>
</p>

<%= link_to 'Edit', edit_coordinator_path(@coordinator) %> |
<%= link_to 'Back', coordinators_path %>